version: "3.1"
services:

  postgresdb:
    container_name: petpostgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: petdoctordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1qaz2wsx

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: petdoctor-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.13-2.6.0
    container_name: petdoctor-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/kafka-logs
    depends_on:
      - zookeeper